#!/bin/bash

# EASIER
PICO_ID=$1
NAME=pico$PICO_ID
ITERATION=$2
#FLAGS=-v

LXC_ROOT=/usr/local/var/lib/lxc/

usage() { 
  echo -e "\nIteratively checkpoint a btrfs-cloned lxc into\n  /checkpoints/picoX/iteration/"
  echo -e "\nUsage:\n  sudo ckpt [pico_id] [iteration#]\n"
} 
if [  $# -le 1 ] 
then 
  usage
  exit 1
fi 
if [[ ( $# == "--help") ||  $# == "-h" ]] 
then 
  usage
  exit 0
fi 
if [[ $USER != "root" ]]; then 
  echo "This script must be run as root" 
  exit 1
fi 

DEST_DIR=/checkpoints/$PICO_ID/$ITERATION
sudo mkdir -p $DEST_DIR
sudo lxc-checkpoint -s -n $NAME $FLAGS -D $DEST_DIR
